service: transaction-request-serverless
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    RPC_URL: ${env:RPC_URL}
    SENTRY_DSN: ${env:SENTRY_DSN}
package:
  excludeDevDependencies: false
functions:
  pay:
    handler: src/handlers/pay.pay
    events:
      - httpApi:
          path: /pay
          method: post
  points-setup:
    handler: src/handlers/points-setup.pointsSetup
    events:
      - httpApi:
          path: /points-setup
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-prune-versions
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4002
    lambdaPort: 4003
  prune:
    automatic: true
    includeLayers: true
    number: 3
